insert into ratings_app_article (title, text) values ('Sports Update', 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.');
insert into ratings_app_article (title, text) values ('Sports Update', 'Et harum quidem rerum facilis est et expedita distinctio.');
insert into ratings_app_article (title, text) values ('Travel Guide', 'Itaque earum rerum hic tenetur a sapiente delectus');
insert into ratings_app_article (title, text) values ('Sports Update', 'id est laborum et dolorum fuga.');
insert into ratings_app_article (title, text) values ('Sports Update', 'Omnis voluptas assumenda est');
insert into ratings_app_article (title, text) values ('Sports Update', 'cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus.');
insert into ratings_app_article (title, text) values ('Breaking News', 'Similique sunt in culpa qui officia deserunt mollitia animi');
insert into ratings_app_article (title, text) values ('Health Tips', 'id est laborum et dolorum fuga.');
insert into ratings_app_article (title, text) values ('Travel Guide', 'Omnis voluptas assumenda est');
insert into ratings_app_article (title, text) values ('Health Tips', 'Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.');
insert into ratings_app_article (title, text) values ('Breaking News', 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.');
insert into ratings_app_article (title, text) values ('Health Tips', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.');
insert into ratings_app_article (title, text) values ('Health Tips', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.');
insert into ratings_app_article (title, text) values ('Travel Guide', 'ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.');
insert into ratings_app_article (title, text) values ('Travel Guide', 'Omnis voluptas assumenda est');
insert into ratings_app_article (title, text) values ('Health Tips', 'Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.');
insert into ratings_app_article (title, text) values ('Tech Insights', 'omnis dolor repellendus.');
insert into ratings_app_article (title, text) values ('Sports Update', 'Nam libero tempore');
insert into ratings_app_article (title, text) values ('Tech Insights', 'Nam libero tempore');
insert into ratings_app_article (title, text) values ('Health Tips', 'Lorem ipsum dolor sit amet');
insert into ratings_app_article (title, text) values ('Tech Insights', 'cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus.');
insert into ratings_app_article (title, text) values ('Breaking News', 'Itaque earum rerum hic tenetur a sapiente delectus');
insert into ratings_app_article (title, text) values ('Breaking News', 'Omnis voluptas assumenda est');
insert into ratings_app_article (title, text) values ('Sports Update', 'Omnis voluptas assumenda est');
insert into ratings_app_article (title, text) values ('Travel Guide', 'consectetur adipiscing elit.');
insert into ratings_app_article (title, text) values ('Sports Update', 'ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.');
insert into ratings_app_article (title, text) values ('Breaking News', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.');
insert into ratings_app_article (title, text) values ('Tech Insights', 'consectetur adipiscing elit.');
insert into ratings_app_article (title, text) values ('Sports Update', 'Similique sunt in culpa qui officia deserunt mollitia animi');
insert into ratings_app_article (title, text) values ('Health Tips', 'omnis dolor repellendus.');
insert into ratings_app_article (title, text) values ('Tech Insights', 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.');
insert into ratings_app_article (title, text) values ('Breaking News', 'Omnis voluptas assumenda est');
insert into ratings_app_article (title, text) values ('Breaking News', 'id est laborum et dolorum fuga.');
insert into ratings_app_article (title, text) values ('Health Tips', 'Et harum quidem rerum facilis est et expedita distinctio.');
insert into ratings_app_article (title, text) values ('Sports Update', 'Lorem ipsum dolor sit amet');
insert into ratings_app_article (title, text) values ('Sports Update', 'Itaque earum rerum hic tenetur a sapiente delectus');
insert into ratings_app_article (title, text) values ('Sports Update', 'id est laborum et dolorum fuga.');
insert into ratings_app_article (title, text) values ('Sports Update', 'Similique sunt in culpa qui officia deserunt mollitia animi');
insert into ratings_app_article (title, text) values ('Travel Guide', 'consectetur adipiscing elit.');
insert into ratings_app_article (title, text) values ('Breaking News', 'omnis dolor repellendus.');
insert into ratings_app_article (title, text) values ('Sports Update', 'Omnis voluptas assumenda est');
insert into ratings_app_article (title, text) values ('Tech Insights', 'cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus.');
insert into ratings_app_article (title, text) values ('Travel Guide', 'cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus.');
insert into ratings_app_article (title, text) values ('Sports Update', 'Omnis voluptas assumenda est');
insert into ratings_app_article (title, text) values ('Travel Guide', 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.');
insert into ratings_app_article (title, text) values ('Tech Insights', 'Itaque earum rerum hic tenetur a sapiente delectus');
insert into ratings_app_article (title, text) values ('Travel Guide', 'id est laborum et dolorum fuga.');
insert into ratings_app_article (title, text) values ('Travel Guide', 'Lorem ipsum dolor sit amet');
insert into ratings_app_article (title, text) values ('Tech Insights', 'omnis dolor repellendus.');
insert into ratings_app_article (title, text) values ('Travel Guide', 'consectetur adipiscing elit.');
